name: Main

on: push

jobs:
  build_test_analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: maven
      - run: ./mvnw --batch-mode --update-snapshots verify
